# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073c4133c68173603398e419d83a2540ef77535c848b4d65d8ab84f31f36f300304b39ec62ed9da49ea206f8b843b74e3097aab392afaaf9934ebed4e7b2c0af

test:
  secret_key_base: eae2ad6a0d0b3fe076a29747e48685bd60d4afffb56c7bee5f3a8fac01980f16917c1d2dc15a0081de481fbb41b5c386fc66ea58d2451e43c011bacc9b79ce2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
